version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - PORT=5000
    networks:
      - app-network
  
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
